# Site settings
title:          Tadej's Blog
description:    "Code, Coffee, Life"
url:            "http://www.tadej.me"

# Author
author:
  name:         Tadej Slamic
  url:          http://www.tadej.me
  email:        tadej.slamic@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

# Permalinks
permalink:      /:title
paginate:       5
