author: Tadej
title: Tadej's Blog
description: "Tadej's Blog - Code, Coffee, Life"
copyright_name: tadej.me

baseurl: ""
url: ""

header-img: img/index.jpg

twitter_username:
github_username:  tslamic
stackoverflow_username: 905349
linkedin_username: tadejslamic
email_recaptcha_url: http://www.google.com/recaptcha/mailhide/d?k=0111lMTscu6dV5C-xqKQJIdw==&c=yuobLsnDzPlkgvE7eDLirgKBMG2TBTHfslypuNTrofQ=

disqus_shortname: tslamic
google_tracking_id: UA-44812127-1

markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
